image: golang

stages:
  - build

build:
  stage: build
  script:
    - GOOS=linux   GOARCH=amd64 make eth2-monitor && mv bin/eth2-monitor{,-linux-amd64}
    - GOOS=darwin  GOARCH=amd64 make eth2-monitor && mv bin/eth2-monitor{,-darwin-amd64}
    - GOOS=freebsd GOARCH=amd64 make eth2-monitor && mv bin/eth2-monitor{,-freebsd-amd64}
    - GOOS=windows GOARCH=amd64 make eth2-monitor && mv bin/eth2-monitor{,-windows-amd64}
  artifacts:
    paths:
      - bin/
